### ISSUE TITLE
Make Test - failure

### ISSUE THREAD

**Issue by kiritigowda** [srohit0/trafficVision#4]
````
kiriti@simon:~/ISV/kiriti/trafficVision$ make test
for vid in media/demo.mp4; do \
	echo processing $vid ;\
	/usr/bin/python ./main.py --video $vid ;\
done
processing media/demo.mp4
('Loaded', 'yoloOpenVX')
OK: loaded 24 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx900) [OpenCL 1.2 ] [SvmCaps 0 1]
OK: annCreateInference: successful
Traceback (most recent call last):
  File "./main.py", line 49, in <module>
    yoloNet = inference.yoloInferenceNet(yoloOpenVX.weights);
  File "/home/kiriti/ISV/kiriti/trafficVision/inference.py", line 28, in __init__
    input_info,output_info = yoloOpenVX.interface.annQueryInference().decode("utf-8").split(';')
ValueError: too many values to unpack
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 1

````

**Comment by conglanjun** [comment]
I have solved it.
https://github.com/srohit0/trafficVision/issues/6
