### ISSUE TITLE
link issue in prepareModel.sh

### ISSUE THREAD

**Issue by dsGoose** [srohit0/trafficVision#6]
Hi,
When I try to do prepareModel.sh I have the following error in linking anntest : 
[100%] Linking CXX executable anntest
//opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::Geometry::initialise(bool, bool, bool, bool, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char)@MIOPENGEMM_1'
/opt/rocm/mivisionx/lib/libvx_nn.so: undefined reference to `MIOpenGEMM::GemmStatus MIOpenGEMM::xgemm<float>(bool, bool, bool, unsigned long, unsigned long, unsigned long, float, _cl_mem*, unsigned long, unsigned long, _cl_mem*, unsigned long, unsigned long, float, _cl_mem*, unsigned long, unsigned long, _cl_mem*, unsigned long, unsigned long, _cl_command_queue**, unsigned int, _cl_event* const*, _cl_event**, int)@MIOPENGEMM_1'

Any idea ?

then when I go to trafficVision and I do make test I have the following error

OK: OpenVX using GPU device#0 (gfx900) [OpenCL 2.0 ] [SvmCaps 0 0]
OK: annCreateInference: successful
TETS
Traceback (most recent call last):
  File "./main.py", line 58, in <module>
    yoloNet = inference.yoloInferenceNet(yoloOpenVX.weights);
  File "/home/goose/GOOSE/YOLO/trafficVision/inference.py", line 29, in __init__
    input_info,output_info = yoloOpenVX.interface.annQueryInference().decode("utf-8").split(';')
ValueError: too many values to unpack
Makefile:8: recipe for target 'test' failed
make: *** [test] Error 1

Can you help ?

Thanks

Regards

G.

**Comment by dsGoose** [comment]
Ok I fixed it :)
 it's running well now

**Comment by srohit0** [comment]
Awesome. 

You mind sharing the solution to benefit other users/developers?

**Comment by conglanjun** [comment]
I meet the same problem. And solve it myself!
yoloOpenVX.interface.annQueryInference().decode("utf-8") # print it shows, XXX;XXX;
so split(';') the result is ['XXX', 'XXX', '']
only need two elements.
so change code to
input_info,output_info = yoloOpenVX.interface.annQueryInference().decode("utf-8")[0:-1].split(';')

or change the config file text, remove the last ';'
